"""generation of tables

Revision ID: 833e4a41c2ad
Revises: 
Create Date: 2025-11-24 13:43:40.278229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '833e4a41c2ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upscaling_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('label', sa.Enum('OPENEO', 'OGC_API_PROCESS', name='processtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'RUNNING', 'FINISHED', 'CANCELED', 'FAILED', 'UNKNOWN', name='processingstatusenum'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('service', mysql.LONGTEXT(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upscaling_tasks_created'), 'upscaling_tasks', ['created'], unique=False)
    op.create_index(op.f('ix_upscaling_tasks_id'), 'upscaling_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_upscaling_tasks_label'), 'upscaling_tasks', ['label'], unique=False)
    op.create_index(op.f('ix_upscaling_tasks_status'), 'upscaling_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_upscaling_tasks_title'), 'upscaling_tasks', ['title'], unique=False)
    op.create_index(op.f('ix_upscaling_tasks_updated'), 'upscaling_tasks', ['updated'], unique=False)
    op.create_index(op.f('ix_upscaling_tasks_user_id'), 'upscaling_tasks', ['user_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('label', sa.Enum('OPENEO', 'OGC_API_PROCESS', name='processtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'RUNNING', 'FINISHED', 'CANCELED', 'FAILED', 'UNKNOWN', name='processingstatusenum'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('platform_job_id', sa.String(length=255), nullable=True),
    sa.Column('parameters', mysql.LONGTEXT(), nullable=False),
    sa.Column('service', mysql.LONGTEXT(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('upscaling_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['upscaling_task_id'], ['upscaling_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_created'), 'processing_jobs', ['created'], unique=False)
    op.create_index(op.f('ix_processing_jobs_id'), 'processing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_label'), 'processing_jobs', ['label'], unique=False)
    op.create_index(op.f('ix_processing_jobs_platform_job_id'), 'processing_jobs', ['platform_job_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_title'), 'processing_jobs', ['title'], unique=False)
    op.create_index(op.f('ix_processing_jobs_updated'), 'processing_jobs', ['updated'], unique=False)
    op.create_index(op.f('ix_processing_jobs_user_id'), 'processing_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_user_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_updated'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_title'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_platform_job_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_label'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_created'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_upscaling_tasks_user_id'), table_name='upscaling_tasks')
    op.drop_index(op.f('ix_upscaling_tasks_updated'), table_name='upscaling_tasks')
    op.drop_index(op.f('ix_upscaling_tasks_title'), table_name='upscaling_tasks')
    op.drop_index(op.f('ix_upscaling_tasks_status'), table_name='upscaling_tasks')
    op.drop_index(op.f('ix_upscaling_tasks_label'), table_name='upscaling_tasks')
    op.drop_index(op.f('ix_upscaling_tasks_id'), table_name='upscaling_tasks')
    op.drop_index(op.f('ix_upscaling_tasks_created'), table_name='upscaling_tasks')
    op.drop_table('upscaling_tasks')
    # ### end Alembic commands ###
